name = "maharaji-kitchen"
main = "dist/server/server.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"
binding = "ASSETS"

[env.production]
name = "maharaji-kitchen"
[env.production.assets]
directory = "dist/client"
binding = "ASSETS"

[env.staging]
name = "maharaji-kitchen-staging"
[env.staging.assets]
directory = "dist/client"
binding = "ASSETS"

[env.preview]
name = "maharaji-kitchen-preview"
[env.preview.assets]
directory = "dist/client"
binding = "ASSETS"
