name = "maharaji-kitchen"
main = "dist/server/index.mjs"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "maharaji-kitchen"

# Staging / non-production branch environment
[env.staging]
name = "maharaji-kitchen-staging"

# Preview / dev branch environment
[env.preview]
name = "maharaji-kitchen-preview"
